
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_test
    username: root
    password: 20000302
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 39.105.195.6
    password: '0302'